### ISSUE TITLE
Documentation needed

### ISSUE THREAD

**Issue by ShreyaSa** [ShreyaSa/little-red-dress#2]
Please add a small nice documentation briefing on the Code of Conduct and a thing or two about how to build a nice resume.

**Comment by sandmanx** [comment]
Would like to work on this.

**Comment by sandmanx** [comment]
@ShreyaSa Solved the issue in the latest pull request. Cheers!!

**Comment by winniehell** [comment]
@ShreyaSa It looks like this is solved. Could you close it or remove the hacktoberfest label?

**Comment by ShreyaSa** [comment]
@winniehell You're right. Closing this issue. Thanks @sandmanx for the help.
